### ISSUE TITLE
log-warper-1.7.6: ‘<>’ is not a (visible) method of class ‘Semigroup’

### ISSUE THREAD

**Issue by juhp** [serokell/log-warper#75]
In Stackage Nightly build:

```
src/System/Wlog/LoggerConfig.hs:133:9: error:
    ‘<>’ is not a (visible) method of class ‘Semigroup’
    |
133 |     lt1 <> lt2 = LoggerTree
    |         ^^
```

**Comment by chshersh** [comment]
@juhp Thanks for reporting this issue! This is because `log-warper` is now using newer version of `universum` package. I see that in [latest nightly resolver](https://www.stackage.org/nightly-2017-12-14) there's still `universum-0.8.0` while actually `log-warper` uses: http://hackage.haskell.org/package/universum-0.9.1

So I guess this will be resolved after new `universum` appears in stackage nightly tomorrow?..

**Comment by juhp** [comment]
Then please add a lower bound on universum.  I can open a PR if you prefer.

I guess I could disable the universum testsuite for fpco/stackage#3100.

**Comment by chshersh** [comment]
@juhp This is now fixed in `log-warper-1.8.1` version: http://hackage.haskell.org/package/log-warper

**Comment by chshersh** [comment]
I see `universum-0.9.1` in latest stackage nightly as well as `log-warper-1.8.1`:
https://www.stackage.org/nightly-2017-12-16

So I think this issue can be closed.

**Comment by juhp** [comment]
Thanks
